### ISSUE TITLE
miniconda libmamba fails(?)

### ISSUE THREAD

**Issue by andzandz11** [dbeisser/Natrix2#1]
Hi, as far as I understand the libmamba solver is the best solver for miniconda.

Unfortunately it does not work with Natrix2(?)

The standard solver is not working for a lot of people because it gets stuck in an endless mode.
https://github.com/conda/conda/issues/11919#issuecomment-1630510730

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides libcurl 7.79.0 h2574ce0_0 needed by curl-7.79.0-hea6ffbf_0
```

Also it looks like it is going to be the new standard: https://conda.org/blog/2023-07-05-conda-libmamba-solver-rollout/

Can you please clarify in the manual what to put in the primer csv file if my primers are already removed?

**Comment by adeep619** [comment]
Hi [andzandz11](https://github.com/andzandz11), thank you for the comment.
I have tried with libmamba solver and it is working fine with Natrix2. please let us know if you encounter any issues.
