### ISSUE TITLE
Issue running Natrix2 with Nanopore 18S example data 

### ISSUE THREAD

**Issue by MP-98-21** [dbeisser/Natrix2#11]
Hello,

I was trying to run Natrix2 on the example data provided. It works correctly with the Illumina data but when trying to use the Nanopore data it gives the following error:
![Pychopper_error](https://github.com/dbeisser/Natrix2/assets/125815921/d53de849-9b5e-4a7f-8305-7f639606edd7)

I also attached a screenshot of the files contained in the Natrix2 folder. It seems the error is related to pychopper but I was able to install it correctly in the conda environment. I also tried using the dev version of Natrix2 and had the same error. 

![Natrix2_files](https://github.com/dbeisser/Natrix2/assets/125815921/688c6fa0-1944-4ac3-a996-6684df1de51d)

Any help or guidance you may have is appreaciated.

Thank you very much,
Miguel

**Comment by MP-98-21** [comment]
Hi Dana,

Thank you for your help! Using the dev-branch and running the example Nanopore data worked, but we are having issues running Natrix with our own data. We are having an error in the rule "make_ncbi_db", where it says some files "nt.000." files were not downloaded correctly or maybe corrupt. And the pipeline won't work due to this.
![image](https://github.com/dbeisser/Natrix2/assets/125815921/e9989395-a5b3-47fe-9ff9-49c478ecafb7)

We tried replacing these files with manually downloaded ones from NCBI but the error persists. And trying the options it gives us with the snakemake commands are not working as we get an error in the Snakefile:
![image](https://github.com/dbeisser/Natrix2/assets/125815921/89815960-1e6f-452b-844e-2118e7252eac)

I also attached the log file of the natrix run. 
[2024-06-11T122121.907859.snakemake.log](https://github.com/user-attachments/files/15809038/2024-06-11T122121.907859.snakemake.log)
We would appreaciate it if you could help us solve this.

Thank you for your help and your time!

Greetings,
Miguel

**Comment by dusti1n** [comment]
> Hi Dana,
> 
> Thank you for your help! Using the dev-branch and running the example Nanopore data worked, but we are having issues running Natrix with our own data. We are having an error in the rule "make_ncbi_db", where it says some files "nt.000." files were not downloaded correctly or maybe corrupt. And the pipeline won't work due to this. ![image](https://private-user-images.githubusercontent.com/125815921/339080086-e9989395-a5b3-47fe-9ff9-49c478ecafb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODg1NjYsIm5iZiI6MTcxOTQ4ODI2NiwicGF0aCI6Ii8xMjU4MTU5MjEvMzM5MDgwMDg2LWU5OTg5Mzk1LWE1YjMtNDdmZS05ZmY5LTQ5YzQ3OGVjYWZiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMTM3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2MyMjI1NWY0NzljNGI5ZDY3YjczMDFjNTUwYTIxMzJiOWI1YTUxMmRiY2U1NmFhNjQ3MzRlNGZkNTAxZDM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zwhzE4j6Q6fO-DAq7-Z89acyXEG8z5KxS3Amg0PUvZo)
> 
> We tried replacing these files with manually downloaded ones from NCBI but the error persists. And trying the options it gives us with the snakemake commands are not working as we get an error in the Snakefile: ![image](https://private-user-images.githubusercontent.com/125815921/339079998-89815960-1e6f-452b-844e-2118e7252eac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODg1NjYsIm5iZiI6MTcxOTQ4ODI2NiwicGF0aCI6Ii8xMjU4MTU5MjEvMzM5MDc5OTk4LTg5ODE1OTYwLTFlNmYtNDUyYi04NDRlLTIxMThlNzI1MmVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMTM3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzAxYThlOGJkZWEzNTJlMzFkZGYxYzMxOWY5ZjY1NWViODNjYWQ0YjFiMDllMzg5MWM3OGEyMmUyMDQxMmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J9X6V6eRCvbP3v-6N-8qf0h-O9Vf4KvifrDFWLy9JoY)
> 
> I also attached the log file of the natrix run. [2024-06-11T122121.907859.snakemake.log](https://github.com/user-attachments/files/15809038/2024-06-11T122121.907859.snakemake.log) We would appreaciate it if you could help us solve this.
> 
> Thank you for your help and your time!
> 
> Greetings, Miguel

**The question has been transferred to the following contribution: https://github.com/dbeisser/Natrix2/issues/15**
