### ISSUE TITLE
inconsistent OTU size value.

### ISSUE THREAD

**Issue by omarkr8** [dbeisser/Natrix2#12]
Hi,

looking through the 2 output  from clustering:

[ vsearch_table.csv ] might have seqid called: N100_17000, N200_500, N300_4
whereas
[ vsearch_all_otus.fasta ] has headers called: >100;size=17000;, >200;size=5000;, >300;size=4;

I assume that in the 3 case above they refer to the same thing. but on occasion i'll find something like:
N191_426 and >191;size=150; , where the total read count from the .csv tallies to 426.
other value differences i'm finding are : size=7 vs _55182 and size=14 vs _54 where it always will be the bigger number (or table value)

I guess the curious thing is how does the tally get reduced from the vsearch table to fasta? and which is the correct one?

**Comment by DanaBlu** [comment]
Hello @omarkr8,

the same issue has already been addressed in #5 and fixed from our side. Please use the latest dev or main branch updates (April 5, 2024). This should fix the issue. 

Best regards,

Dana

**Comment by omarkr8** [comment]
after having a think perhaps i've misunderstood the headers. Could it be that the fasta headers ("size=x) refer to the dereplicated read being used to represent the cluster (and identical copies of that read). whereas the "_x" refers to number of reads in the vsearch% cluster?

in any case, im going to try the current dev branch now.

**Comment by DanaBlu** [comment]
The first number in the header of vsearch_all_otus.fasta refers to the ID of the representative of the cluster and the second number stands for the number of sequences assigned to this cluster.

>12613;size=8;
TTCGTTCAGTTACGTATTGCTAAGGTTAAGAGAGGACAAAGGTTTCAACGCTTCAGCACCTGTCGCTCCTACTGATTGAA
TTTTGTGATGAGGACCTTGGACTGTAGACGCATGTATTTAGTAGGATTGTCGAAGAGTCAGAGGAAGCATGATAGCTATA
CTTGTATAGATTATCTTATAGAAATTTGTTCGAATCTTGCAATTTAGAAGAAGGAGAAGTCGTAACAAGGTCTTC

For example, here the representative sequence would be the sequence with the ID=12613 and in total 8 sequences were either identical or within the set clustering threshold and were assigned to that sequence. If you would like to see which sequences were assigned to that cluster please have a look at the vsearch_all_otus_tab.txt. 

For further processing, only the representative sequence of each cluster is used and not a consensus sequence of the sequences within a cluster. 

Please comment again if you have any further questions or issues!

Dana
