### ISSUE TITLE
manually running each step

### ISSUE THREAD

**Issue by omarkr8** [dbeisser/Natrix2#13]
Im wondering if instead of running the .yaml and executing the entire workflow; we could use the existing tools to run the steps separately?

i imagine the commands to do so are already in the files somewhere, and maybe i just need to be pointed out where to look for them? 

i ask this for two reasons:
1) having the multiqc and filtering step immediately go through to downstream process can be troublesome if you need to actually refine the variables, or exclude samples before proceeding. so being able to rerun this portion separately is ideal.
2) it seems some tools and packages have version incompatibilities and break. (i.e. everytime i do a fresh install of natrix, i have to go into a script to change "append" into "_append", or something like that.  being able to run the pipeline in a modular fashion make me feel less concerned about changing little pieces here and there when needed.

**Comment by dusti1n** [comment]
Hi @omarkr8, you could specifically run a certain rule with the following command after you have created your dataframe. All dependencies required for the rule will be included automatically. This allows you to execute individual rules specifically with your selected samples. Best, Dustin
`snakemake -R --until rulename --use-conda --cores all --configfile configfile.yaml`
