### ISSUE TITLE
vsearch_id parameter not provided

### ISSUE THREAD

**Issue by willem-stock** [dbeisser/Natrix2#14]
it seems that in the latest version, the vsearch_id parameter has been introduced but it is not provided by the (example) yaml and no default value is given. As a quick fix, i reverse the changes in rules/vsearch_clust.smk;  setting vsearch id back to 0.98.

regards

**Comment by omarkr8** [comment]
hi, non-technical user here. wondering how you figured out the id wasnt provided. i imagine vsearch wouldnt run if a --id value wasnt specified?

**Comment by DanaBlu** [comment]
Hello @willem-stock,
thank you for reporting this problem! I'm a bit surprised as this has never happened with us before. Could you please provide us know your error message so we can find out what the problem is?
Best regards,
Dana

**Comment by dusti1n** [comment]
> sorry, I was not specific enough. the vsearch_id paramater was introduced within the snakemake workflow (params: id=config["vsearch_id"] in the rule vsearch_clust). when initiating the snakemake from the latest version of Natrix2, it threw an error when compiling the DAG

Hi @willem-stock, what exactly kind of error do you have when you want to create a DAG plot?
