### ISSUE TITLE
Issue running Natrix2 with Nanopore data (dev-branch)

### ISSUE THREAD

**Issue by MP-98-21** [dbeisser/Natrix2#15]
Hello,

We were using the dev-branch and running the example Nanopore data and it worked correctly without errors, but we are having issues running Natrix with our own data (also Nanopore data). We are having an error in the rule "make_ncbi_db", where it says some files "nt.000." files were not downloaded correctly or maybe corrupt. And the pipeline won't work due to this.
![image](https://github.com/dbeisser/Natrix2/assets/125815921/45609713-41d3-4849-9aba-b35785d4a3bb)

We tried replacing these files with manually downloaded ones from NCBI but the error persists. And trying the options it gives us with the snakemake commands are not working as we get an error in the Snakefile:
![image](https://github.com/dbeisser/Natrix2/assets/125815921/47fc964b-0299-45d5-adea-b5fd16af17dd)

I also attached the log file of the natrix run.
[2024-06-11T122121.907859.snakemake.log](https://github.com/user-attachments/files/15825749/2024-06-11T122121.907859.snakemake.log)

We would appreaciate it if you could help us solve this.

Thank you for your help and your time!

Greetings,
Miguel

**Comment by dusti1n** [comment]
Hello @MP-98-21,

can you perhaps tell me which config file you are using? Maybe you can upload it so that I can have a look at it.
I have tested the rule '**make_ncbi_db'** with Nanopore data. I did not get an error message. The database was created completely. Maybe it's a small mistake. I will have a look at your config file and check it with Nanopore data.

Best,
Dustin

**Comment by MP-98-21** [comment]
Hi Dustin,
[COI2.zip](https://github.com/user-attachments/files/16016419/COI2.zip)

Sure, here is the config file we are using. I attached it as a zipped file as GitHub won't let me attach the .yaml file directly. If you cannot download it, let me know if I can send you the file another way. 

Thanks for your help!

Greetings,
Miguel

**Comment by dusti1n** [comment]
> Hi Dustin, [COI2.zip](https://github.com/user-attachments/files/16016419/COI2.zip)
> 
> Sure, here is the config file we are using. I attached it as a zipped file as GitHub won't let me attach the .yaml file directly. If you cannot download it, let me know if I can send you the file another way.
> 
> Thanks for your help!
> 
> Greetings, Miguel

Great, thanks for uploading it. I'll have a look at the configuration file and run a test.

Best,
Dustin

**Comment by dusti1n** [comment]
Hello @MP-98-21,

I tested your config file with Nanopore data and did not encounter any issues with the NCBI database. I also used the natrix2/dev branch. Perhaps you could set up the entire environment again and restart the workflow on a current system. It might be that the blast.smk contains errors. The best approach would be to set everything up again and carry out the steps manually.

I noticed that the 'memory' parameter in your config file is set to 80. That seems a bit low to me. It is important that the RAM in the 'memory' parameter is always specified in megabytes.

For example, if you want to use 7GB (7000 is also okay):
```yaml
general:
        memory: 7168 # Available RAM in MB.
```
After setting up the environment with Conda and installing everything, I created the data frame and started the workflow with the following commands:
```shell
python3 create_dataframe.py COI2.yaml
```
```shell
snakemake --use-conda --cores all --configfile /path/to/COI2.yaml
```

If you have any further questions, please do not hesitate to contact us!

Best regards,
Dustin

**Comment by MP-98-21** [comment]
Hi Dustin,

Thanks for your response and your help! You are right we did not notice about the memory parameter, we already corrected this. We tried following your suggestions. The data frame was correctly created and everything seemed to be running smoothly but we are having the same problem with the make_ncbi_database rule. I don't know why but now we are getting this error:
![Natrix_error](https://github.com/dbeisser/Natrix2/assets/125815921/653b058e-1692-4413-a99d-1684ac837bab)

It seems there is a problem downloading the database again. I don't know why it works for you but not for us. I also tried downloading the database files manually and then running: snakemake --use-conda --cores all --configfile /path/to/COI2.yaml. But I could not find a way to bypass the automatic instalation of the nt NCBI database. Maybe that could be the solution, if we could download it manually and prevent the script from downloading it again?

Thanks for your help and your time!

Best,
Miguel

**Comment by MP-98-21** [comment]
Hi Dustin,

Thank you for your response! We tried installing each file manually and it seems to be working, just taking a bit of time. Thanks also fot the command to check if the files are corrupt or not. Right now we are encountering another problem, now related to the polishing step with racon: 
![image](https://github.com/user-attachments/assets/534cf380-b6e1-4cfa-9b5a-bbe74ab9fff2)

Let me know if you have any suggestions on how to solve this error. 

Thanks again for all your help!

Best,
Miguel

**Comment by dusti1n** [comment]
Hello Miguel,

Thank you very much for your feedback.

It would be very helpful if you could provide your Snakemake log file. Please check the input files you are using for Racon to ensure they are not empty or incorrect. Have you tried starting the workflow with test data? This way, you can rule out the possibility that the input files are corrupted, which is a common issue. Path problems, file permissions, or insufficient hardware resources can also often lead to errors. It would be great if you could provide us with your Snakemake log file. 

If the problem persists, we would be happy to assist you further.

Best regards,
Dustin
