### ISSUE TITLE
pychop error

### ISSUE THREAD

**Issue by dmgr90** [dbeisser/Natrix2#16]
Hi!

Im getting this error while trying to run natrix2 on my nanopore data. 

KeyError in line 2 of /ictstr01/home/haicu/daniel.gygax/big_zambia/db_test/natrix2/Natrix2/rules/pychop.smk:
'nanopore'
  File "/ictstr01/home/haicu/daniel.gygax/big_zambia/db_test/natrix2/Natrix2/Snakefile", line 57, in <module>
  File "/ictstr01/home/haicu/daniel.gygax/big_zambia/db_test/natrix2/Natrix2/rules/pychop.smk", line 2, in <module>

I am using the dev-branch as recommended in another issue. I additionally installed pychopper in the environment (it wasnt installed before). 
Names of the csv and yaml seem to be correct.

As a note: Before I was getting the same error as in issue#11. 

Thank you for your help :)

**Comment by dusti1n** [comment]
Hello @dmgr90,

If the entry does not yet exist in the config file, please open your config file and add the boolean value '**pychopper: TRUE**', preferably directly under '**nanopore: TRUE**'. This should solve your problem. If not, please contact us again and we will find a solution.

Here is an example of what the entry should look like:

```yaml
dataset:
    nanopore: TRUE
    pychopper: TRUE
```

Can you please tell me which configuration file you are using?

Best regards,
Dustin

**Comment by dmgr90** [comment]
Hi Dustin!

Thank you very much for the quick answer. Your comment made me check. As it turns out, when I started using the dev branch, I kept the .yaml file form the main-branch. Now I am using the correct one and seems to be working, Running for 17h now and going.

Thank you!

**Comment by dusti1n** [comment]
Great to hear! If you have any further questions, please feel free to contact us.

Best, 
Dustin
