### ISSUE TITLE
Error in rule quality_filtering:

### ISSUE THREAD

**Issue by dmgr90** [dbeisser/Natrix2#18]
Hi!!

I have been getting the error below. I am running the dev-branch on myy own nanopore data. My input fastq files seem to be fine at a first glance. I am using very low quality thresholds in al instances (i.e 7), so all data should pass the quality filters.
Do you know how could I solve or circumvent this issue? 

Thank you in advance for your support. 

Daniel

**Error:**

...Finished job 83.
25 of 561 steps (4%) done

[Fri Jul 12 14:22:21 2024]
rule quality_filtering:
    input: output_db_test/fastq/COP3A212SV5_A_1.tmp
    output: output_db_test/quality_filtering/COP3A212SV5_A_R1.fastq
    jobid: 60
    wildcards: sample=COP3A212SV5, unit=A
    threads: 20

Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Select jobs to execute...
Activating conda environment: /ictstr01/home/haicu/daniel.gygax/big_zambia/db_test/natrix2/Natrix2/.snakemake/conda/ffcc3184

thread 'thread '<unnamed><unnamed>' panicked at ' panicked at src/main.rssrc/main.rs::168168thread ':<unnamed>:' panicked at 4141src/main.rs:
:
:thread 'ERROR: problem parsing fastq record: IncompleteRecordERROR: problem parsing fastq record: IncompleteRecord<unnamed>168

' panicked at thread ':note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
src/main.rs41<unnamed>::
168' panicked at ERROR: problem parsing fastq record: IncompleteRecord:src/main.rs41
::
168ERROR: problem parsing fastq record: IncompleteRecord:
41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at src/main.rs:168thread ':<unnamed>41' panicked at :
src/main.rsERROR: problem parsing fastq record: IncompleteRecordthread ':
<unnamed>168' panicked at :src/main.rs41:thread ':
168<unnamed>:' panicked at ERROR: problem parsing fastq record: IncompleteRecord41
src/main.rs:
:ERROR: problem parsing fastq record: IncompleteRecord168
:41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at src/main.rs:thread '168<unnamed>:' panicked at 41src/main.rs:
thread ':ERROR: problem parsing fastq record: IncompleteRecord<unnamed>168' panicked at :
src/main.rs41::
168ERROR: problem parsing fastq record: IncompleteRecord:
41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at src/main.rs:168:41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at src/main.rs:thread '168<unnamed>:' panicked at 41src/main.rs:
:ERROR: problem parsing fastq record: IncompleteRecord168thread '
:<unnamed>41' panicked at :
src/main.rsERROR: problem parsing fastq record: IncompleteRecord:
168:41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at thread 'src/main.rs<unnamed>:' panicked at 168:src/main.rs41::
168ERROR: problem parsing fastq record: IncompleteRecord:
41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at src/main.rs:168:41:
ERROR: problem parsing fastq record: IncompleteRecord
thread '<unnamed>' panicked at src/main.rs:168:41:
ERROR: problem parsing fastq record: IncompleteRecord
[Fri Jul 12 14:22:42 2024]
**Error in rule quality_filtering:
    jobid: 60
    output: output_db_test/quality_filtering/COP3A212SV5_A_R1.fastq
    conda-env: /ictstr01/home/haicu/daniel.gygax/big_zambia/db_test/natrix2/Natrix2/.snakemake/conda/ffcc3184
    shell:
        
                cat output_db_test/fastq/COP3A212SV5_A_1.tmp | chopper --quality 7 --minlength 80 --maxlength 300 --headcrop 0 --tailcrop 0 --threads 20 > output_db_test/quality_filtering/COP3A212SV5_A_R1.fastq
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job quality_filtering since they might be corrupted:
output_db_test/quality_filtering/COP3A212SV5_A_R1.fastq
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message**

**Comment by dusti1n** [comment]
Hello Daniel,

Thank you for contacting us and providing detailed information about the error you are experiencing.

The problem seems to be due to the FASTQ file output_db_test/fastq/COP3A212SV5_A_1.tmp containing incomplete or corrupt records. Check whether the FASTQ file is formatted correctly and does not contain any incomplete data records. Have you tested another data set?

Try adjusting the quality threshold. As you are using a very low threshold, you should try increasing it slightly, as very low thresholds can allow poor-quality sequences through, which can lead to errors in subsequent processing steps. Perhaps you could first increase the threshold to test this.

If the problem persists, you are welcome to contact us again.

Best regards,
Dustin

**Comment by dmgr90** [comment]
Hi Dustin,

Thank you very much for your support. Indeed, I was careless and did not notice that some of my fastq files had empty sequences. This was the source of the issue. I cleaned them and then it worked. 

Thank you again!

**Comment by dusti1n** [comment]
> Hi Dustin,
> 
> Thank you very much for your support. Indeed, I was careless and did not notice that some of my fastq files had empty sequences. This was the source of the issue. I cleaned them and then it worked.
> 
> Thank you again!

Hello Daniel,

Great, that's good to hear that it's working now! If you have any questions, you can contact us at any time.

Best regards,
Dustin
