### ISSUE TITLE
custom_database

### ISSUE THREAD

**Issue by dmgr90** [dbeisser/Natrix2#20]
Hi!

I have a question regarding the use of a custom database to blast on? Are there any files that need to accompany the database? Any specific format. I want to have everything ready to avoid the pipeline to try to connect to NCBI since I often get connection problems. 

Thank you in advance for any information :)

**Comment by dmgr90** [comment]
--2024-08-09 10:17:27--  ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz
           => ‘/lustre/groups/hpc/urban_lab/datasets/ncbi/natrix/.listing’
--2024-08-09 10:17:27--  ftp://ftp.ncbi.nlm.nih.gov/blast/db/
           => ‘.listing’
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.11130.14.250.7, , 130.14.250.10130.14.250.31, , 130.14.250.31130.14.250.12, ..., ...

Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.11|:21... Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.7|:21... failed: Connection timed out.
failed: Connection timed out.
I cant seem to get past this, no matter the quality of the connection

**Comment by dusti1n** [comment]
Thank you for providing the details of your issue. You can try manually downloading the required files for the BLAST database and placing them in the appropriate directory (e.g., database/ncbi/). As long as all the necessary files are in place, Snakemake should utilize the local files without any issues. However, please note that Snakemake might still attempt to establish a brief connection to synchronize or validate the files.

If this approach doesn't resolve the issue, there could be other factors at play, such as a firewall blocking the connection. Unfortunately, an offline mode isn't currently configurable within the Snakemake settings. If you could share your configuration file with me, I'd be happy to take a closer look and help you troubleshoot further.

If you have any additional questions, feel free to reach out at any time.

Best regards,
Dustin
