### ISSUE TITLE
Question over indicating the location of the nt database 

### ISSUE THREAD

**Issue by smartise** [dbeisser/Natrix2#26]
hello, 

first of all many thanks for the work and effort to pile this workflow. 
I am attending to use the pipeline however I fail to find where I can indicate where my already downloaded nt database is located so it avoid downloading a new one. 

when I indicate in in the yaml document, it gives me back an error 

```

Reading file /mnt/ebe/AmpliconSequencingONT/eDNA_nanopore_test/results/filtering/filtered.fasta 100%  
251878 nt in 361 seqs, min 308, max 1146, avg 698
Masking 100% 
Sorting by length 100%
Counting k-mers 100% 
Clustering 0%BLAST Database error: No alias or index file found for nucleotide database [/mnt/ebe/blobtools/nt] in search path [/srv/home/ocol0007/Natrix2::]
[Thu Nov 21 19:59:55 2024]
Error in rule blast:
    jobid: 61
    output: /mnt/ebe/AmpliconSequencingONT/eDNA_nanopore_test/results/blast/blast_taxonomy.tsv
    conda-env: /srv/home/ocol0007/Natrix2/.snakemake/conda/6470f7bb
    shell:
        blastn -num_threads 20 -query /mnt/ebe/AmpliconSequencingONT/eDNA_nanopore_test/results/filtering/filtered.fasta -db /mnt/ebe/blobtools/nt -max_target_seqs 10 -perc_identity 80.0 -evalue 1e-20 -outfmt "6 qseqid qlen length pident mismatch qstart qend sstart send gaps evalue staxid sseqid" -out /mnt/ebe/AmpliconSequencingONT/eDNA_nanopore_test/results/blast/blast_taxonomy.tsv
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job blast since they might be corrupted:
/mnt/ebe/AmpliconSequencingONT/eDNA_nanopore_test/results/blast/blast_taxonomy.tsv
Clustering 100%  
Sorting clusters 100%
Writing clusters 100% 
Clusters: 350 Size min 1, max 5, avg 1.0
Singletons: 342, 94.7% of seqs, 97.7% of clusters
Writing OTU table (classic) 100%  
[Thu Nov 21 19:59:56 2024]
Finished job 56.
56 of 66 steps (85%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /srv/home/ocol0007/Natrix2/.snakemake/log/2024-11-21T194139.868399.snakemake.log
$ 
 ```

I assume the program is trying to compile a new one at the location but I don't see where I can indicate that it' already compiled and ready to use. 

thanks

**Comment by dusti1n** [comment]
Hello,

thank you for describing the problem in detail, and thank you for the feedback on the pipeline—we’re glad to hear that you’re using it! The default path for the NCBI database in the pipeline is:

```yaml
blast:
    blast: TRUE
    database: NCBI
    db_path: database/ncbi/nt
```
**It would be great if you could share your configuration file for your samples so I can review it and ensure everything is set up correctly.** To make sure everything runs smoothly, please also check that the following files are present in the specified directory: e.g., `.nhd`, `.nhi`, `.nhr`, `.nin`, `.nnd`, `.nni`, `.nog`, `.nsq`

These files are required for the pipeline to function as expected. If any are missing, you may need to re-download the database.

**To avoid any further issues, we recommend using the default path (database/ncbi/nt) for the database in the pipeline and placing all required database files there. This ensures compatibility and reduces potential errors.**

If you have any other questions or need further support, feel free to reach out anytime—we’re happy to assist!

Best regards,
Dustin

**Comment by dusti1n** [comment]
Hello @smartise , 

Thank you for sharing your configuration file!

It seems the issue might be with the db_path setting. Currently, it is:

```yaml
db_path: /mnt/ebe/blobtools/nt/nt
```

From the files you provided, it looks like the database files are in `/mnt/ebe/blobtools/nt`. Please update the db_path to:

```yaml
db_path: /mnt/ebe/blobtools/nt
```

**The extra `/nt` might be causing the issue. Additionally, it’s possible that not all required files are present, in which case I recommend re-downloading the database automatically within the workflow.**

**If the issue persists, using the default path for the database and letting the workflow download it automatically might also resolve the problem.**

Let me know if you need further assistance!

Best regards, Dustin

**Comment by smartise** [comment]
hello, thanks for you reply. 

unfortunately the error remains the same. 

```BLAST Database error: Database memory map file error
[Mon Nov 25 21:44:17 2024]
Error in rule blast:
    jobid: 34
    output: /mnt/ebe/AmpliconSequencingONT/natrix_test/results/blast/blast_taxonomy.tsv
    conda-env: /srv/home/ocol0007/Natrix2/.snakemake/conda/8369bbc2
    shell:
        blastn -num_threads 40 -query /mnt/ebe/AmpliconSequencingONT/natrix_test/results/filtering/filtered.fasta -db /mnt/ebe/blobtools/nt -max_target_seqs 10 -perc_identity 90.0 -evalue 1e-20 -outfmt "6 qseqid qlen length pident mismatch qstart qend sstart send gaps evalue staxid sseqid" -out /mnt/ebe/AmpliconSequencingONT/natrix_test/results/blast/blast_taxonomy.tsv
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job blast since they might be corrupted:
/mnt/ebe/AmpliconSequencingONT/natrix_test/results/blast/blast_taxonomy.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /srv/home/ocol0007/Natrix2/.snakemake/log/2024-11-25T214007.137268.snakemake.log
$ 
```

however when I do the blast separately from the pipeline, it does work. with the working directory /mnt/ebe/blobtools/nt/nt

**Comment by dusti1n** [comment]
Hello @smartise,

I have reviewed this process, and the safest approach is to let Natrix2 download the database completely and correctly. This ensures that all required input and output files are in place, avoiding potential errors. I hope this clarifies why the current setup doesn’t work. It’s best to let the pipeline run fully once. This way, you can reuse it for various samples without needing to download the database again.

Please using the standard db_path:

```yaml
db_path: database/ncbi/nt
```

**This will check if the database download works properly. Natrix2 processes the database as follows: The pipeline searches the specified `db_path` for packed database files, such as `nt.000.tar.gz`, `nt.001.tar.gz`, etc. If these packed files are found, Natrix2 unpacks them. Each .tar.gz file contains the following database components:**

```
.nhd
.nhi
.nhr
.nin
.nnd
.nni
.nog
.nsq
Additional files like taxdb.btd, taxdb.bti, and taxonomy4blast.sqlite3.
```

**If the packed files are not found, Natrix2 automatically downloads them, unpacks them, and verifies their content.**


Feel free to reach out if you have any further questions or need assistance. Let me know if your pipeline setup works correctly!

Best regards, dustin

**Comment by smartise** [comment]
hello Dustin, 

thank you very much for your reply. 
Since our cluster has very limited space, I cannot redownload the whole ncbi database for my personal use. 

I just have one last question however. is it possible to resume the pipeline after the error that stop the pipeline ?. I am not familiar with snake make and I don't know if I can just do the blast after the error and then resume the rest of the pipeline in some kind of way

**Comment by dusti1n** [comment]
Hello @smartise,

To continue the workflow without running BLAST again, the blast_taxonomy.tsv file must be present in the following location:

```
/mnt/ebe/AmpliconSequencingONT/natrix_test/results/blast/blast_taxonomy.tsv
```

If this file is correctly placed, you can resume the workflow by running:

```
snakemake --rerun-incomplete -j 40
```

This will only execute the missing or failed steps.

As mentioned before, the best practice is to let the workflow run completely to avoid potential issues. You have two options:

1. Disable BLAST in your configuration file:
By setting blast: FALSE, the pipeline will skip the BLAST step and continue with the remaining analysis. However, without BLAST, taxonomic assignment will not be performed.

2. Continue the workflow:
Ensure that all necessary output files (like blast_taxonomy.tsv) are in place. This will allow the pipeline to proceed with taxonomic assignment and subsequent steps.

Be aware that manually providing files might still cause issues if other dependencies are missing or not properly aligned with the pipeline's requirements.

We are delighted that you are using our pipeline.
Let me know if you have further questions!

Best regards, 
dustin

**Comment by dusti1n** [comment]
I hope your issue has been resolved. Should you have any further questions, please don’t hesitate to contact us at any time. Wishing you joyful holidays and a wonderful start to the new year!

Best regards, 
dustin
