### ISSUE TITLE
NCBI filtering

### ISSUE THREAD

**Issue by omarkr8** [dbeisser/Natrix2#7]
hello, very cool pipeline i wanted to test out.

about the NCBI BLAST options.
Does the tax filtering work on the database download?
i.e. does the entire ncbi database get downloaded regardless?

and so if i want a specific subset of taxa to make a database, i'd have to make a custom one and specify it to be used in the .yaml?

**Comment by DanaBlu** [comment]
Hi @omarkr8,
thanks for the question and for using Natrix2. 
The entire NCBI database is downloaded regardlessly of the tax filtering. 
We are planning to add the option to use your custom database. At the moment it is not possible yet within the configuration file, but we try to implement that soon.
If you have any other questions regarding Natrix2, please feel free to ask!
Best,
Dana

**Comment by DanaBlu** [comment]
Hi @omarkr8,
Thank your for your question!
The NCBI database is downloaded in full, regardless of the tax filtering parameters you specify. 
If you want to use a specific subset of taxa, you need to create a custom database and specify the path in the configuration.yaml file. Please make sure that the custom database still meets the requirements of the desired database format. 
If you have any further questions, please do not hesitate to contact us!
Best,
Dana

**Comment by omarkr8** [comment]
I attempted this. downloading a set of fastas and using makeblastdb commands to get a database folder. 

when i specified the database path on the yaml, it just attempted to download the entire NCBI again in that folder. 
is there some kind of checklist it's going through to determine whether to download NCBI or use existing database?

**Comment by adeep619** [comment]
Hi there, 
the pipeline is currently downloading the database from NCBI. Unfortunately, there is no option for a custom database at the moment. However, I am working on adding this feature and will update it soon. Thank you, Aman.

**Comment by omarkr8** [comment]
thanks. that makes sense from what ive seen.
