### ISSUE TITLE
Nanopore data

### ISSUE THREAD

**Issue by Jorn-Bethke** [dbeisser/Natrix2#8]
Hi I'm just starting to use Natrix and when I ran the ./pipline.sh with Nanopore project got a problem with multiqc reports so the pipeline stops. Here is the snakemake log file 
[Natrix2.snakemake.log](https://github.com/dbeisser/Natrix2/files/14775208/Natrix2.snakemake.log)

hope you can help me solve the issue.

thanks

**Comment by DanaBlu** [comment]
Hi @Jorn-Bethke,

could you please provide me your config.yaml file? It seems like some of the neccessary steps of the pipeline are not conducted.

Best,

Dana

**Comment by Jorn-Bethke** [comment]
Hi Dana thanks for the quick response. I just cloned the dev branch of the repository and run the /pipeline.sh and when it asked for protect is wrote Nanopore assuming that is the configuration yaml file needed that comes with the repository

**Comment by DanaBlu** [comment]
Hi @Jorn-Bethke,
yes, Nanopore.yaml is the correct configuration file with the default parameters you need to process Nanopore data. Could you please upload the file with the changes you have made to the file? There might be a problem with some of the parameters in the file for your specific data.

**Comment by Jorn-Bethke** [comment]
I didn't change anything, I just cloned the dev branch and then I run the ./pipeline.sh command Using the Illumina projects the pipeline works but when I use the Nanopor yaml file I got the multiqc error and the pipeline stops

**Comment by DanaBlu** [comment]
Okay, now I understand the problem! 
We have not yet made the necessary changes in the dev branch to be able to use the Nanopore test dataset without adjusting the file information parameters in the Nanopore.yaml configuration file. I have now done this and you should be able to do a test run with the Nanopore dataset by cloning the dev branch and starting the pipeline with ./pipeline.sh without making any changes to the configuration file.

If you want to run your own dataset, you will need to change the required parameters in the configuration file. 
Please contact us if you need help setting up the configuration file for your custom dataset.

Best,
Dana

**Comment by Jorn-Bethke** [comment]
Thanks, Dana, I will do so and get in touch if needed. 

best, Jorn
