### ISSUE TITLE
pychopper on empty fastqs

### ISSUE THREAD

**Issue by omarkr8** [dbeisser/Natrix2#9]
this might be more of a pychopper issue than a natrix one, but seems like if post-QC leads to a empty (0 read) fastq, and that goes into pychopper, it crashes. something about dividing by length of read (which would be zero). 

perhaps there should be a fastq length check to skip empty files ?

**Comment by DanaBlu** [comment]
Hi @omarkr8,
thank you for reporting this problem. Could you please provide me with the actual error message (check out the log file in .snakemake/log) so I can check what exactly is causing the error and how we can prevent it?
Best, 
Dana

**Comment by omarkr8** [comment]
strangely the error isnt stored in the log files? just the terminal output. 
I'll try and recreate it and send it over later.

**Comment by omarkr8** [comment]
ok here's the output. the bits in bold are not stored in the log. its a fasta with a single sequence ( a failed sample), so when that got filtered out, downstream functions ended up working with empty files.

[Tue Apr  2 23:12:06 2024]
rule pychop:
    input: smart_results/ontime_72htest/quality_filtering/barcode16.72h_A_R1.fastq, smart_results/ontime_72htest/pychopper/custom_primers.fasta, smart_results/ontime_72htest/pychopper/config_primers.txt
    output: smart_results/ontime_72htest/pychopper/output/barcode16.72h_A_R1.tmp, smart_results/ontime_72htest/pychopper/reports/barcode16.72h_A_R1.pdf, smart_results/ontime_72htest/pychopper/unclassified/barcode16.72h_A_R1.tmp, smart_results/ontime_72htest/pychopper/rescued/barcode16.72h_A_R1.fastq, smart_results/ontime_72htest/pychopper/unclassified/barcode16.72h_A_R1_length_out.tmp
    jobid: 12
    wildcards: sample=barcode16.72h, unit=A
    threads: 4

**Activating conda environment: /home/omarkr/Natrix2/.snakemake/conda/1efcaf62
Using kit: PCS109
Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
Counting fastq records in input file: smart_results/ontime_72htest/quality_filtering/barcode16.72h_A_R1.fastq
Total fastq records in input file: 0
Tuning the cutoff parameter (q) on 0 sampled reads (100.0%) passing quality filters (Q >= 7.0).
Optimizing over 30 cutoff values.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 2995.08it/s]
Traceback (most recent call last):
  File "/home/omarkr/Natrix2/.snakemake/conda/1efcaf62/bin/pychopper", line 10, in <module>
    sys.exit(main())
  File "/home/omarkr/Natrix2/.snakemake/conda/1efcaf62/lib/python3.10/site-packages/pychopper/scripts/pychopper.py", line 480, in main
    args.q, class_reads[best_qi] * 100 / len(read_sample)))
ZeroDivisionError: division by zero**

**Comment by DanaBlu** [comment]
Hello @omarkr8,
I would suggest you to remove the corresponding file from your input folder and from the primer table csv file. At the moment, skipping empty files in the pipeline is not possible, but we are aware of this issue.
So for now the easiest way is to delete the corresponding fastQ files and start the pipeline again without these files.
Best,
Dana

**Comment by omarkr8** [comment]
thanks . yes thats what i have been doing to proceed.
must the primer table file be updated? it wont like that some rows dont have associated fastqs?
